### ISSUE TITLE
What defines a driver?

### ISSUE THREAD

**Issue by karlek** [karlek/lapis#2]
Keyboard handler is clearly a driver, but is `fpu.c` a driver? Is `video.c` a driver?

- `fpu.c` communicates with a chipset to enable featues, therefore you could call it a driver (I guess?).
- `video.c` consists more of helper functions to make the DMA access more manageable.

**Comment by mewmew** [comment]
For me intuitively, fpu doesn't feel like a driver, whereas video is perhaps closer to a driver, and keyboard handler is definitely a driver.

When in doubt, just place the source code in the `spork` directory, right next to the `drivers` dir :)

```
src/boot/
src/kernel/
src/kernel/drivers/
src/kernel/spork/
```
