### ISSUE TITLE
Global include problema in "terminal-font.h"

### ISSUE THREAD

**Issue by karlek** [karlek/lapis#9]
After the big header explosion of 2022, clangd now works, but `large_font` no longer works.

I spent a better part of an hour trying to figure out how to export a global variable in C, but to no success.

Maybe @mewmew knows the arcane knowledge of the an __c__ ients?

https://github.com/karlek/lapis/commit/435a228145004e4dc0b8f9f61499ef2a11c2a990

**Comment by mewmew** [comment]
> After the big header explosion of 2022, clangd now works, but large_font no longer works.

Really nice commit though! I feels to much better reading C code that doesn't do `#include "foo.c` :P

We'll figure out the linking issues, no worries! Pinged you on Discord

**Comment by karlek** [comment]
```
$ make clean; CC=clang make bin/kernel.o
$ nm bin/kernel.o | grep large_font
                 U large_font
```

Seems that it's not compiled into the obj file :thinking: 

Edit: solved it! https://github.com/karlek/lapis/pull/11
